import type { Receta } from '../contracts'

// Fuente: docs/productos, tabla "2. Recetario y costeo de cócteles" (18 cócteles).
//
// ALERTA (docs/context.md): existen DOS versiones del recetario que no coinciden
// entre sí. Aquí se cargó la de docs/productos. Confirmar la vigente con el gerente
// antes de operar — p. ej. Martini Sucio cambia de ginebra a vodka entre versiones.
//
// Las garnituras (marcadas `garnitura: true`) traen cantidad estimada: el recetario
// las describe en texto ("gajo de naranja") sin dosis. Confirmar con el gerente.
//
// `costoDoc` es el costo que declara el recetario del cliente. La pantalla de Recetas
// lo contrasta contra el costo calculado desde los ingredientes.

const g = (insumoId: string, cantidad: number) => ({ insumoId, cantidad, garnitura: true })

export const RECETAS: Receta[] = [
  {
    id: 'REC-01',
    nombre: 'Centella',
    cristaleria: 'Old Fashioned',
    metodo: 'Construido',
    garnitura: 'Gajo de toronja',
    precio: 130,
    costoDoc: 26.04,
    ingredientes: [
      { insumoId: 'INS-01', cantidad: 45 },
      { insumoId: 'INS-12', cantidad: 15 },
      { insumoId: 'INS-28', cantidad: 60 },
      { insumoId: 'INS-18', cantidad: 60 },
      { insumoId: 'INS-24', cantidad: 15 },
      { insumoId: 'INS-17', cantidad: 150 },
      g('INS-28', 30),
    ],
  },
  {
    id: 'REC-02',
    nombre: 'Tinto de Verano',
    cristaleria: 'Copa de vino',
    metodo: 'Construido',
    garnitura: 'Rodaja limón eureka',
    precio: 145,
    costoDoc: 28.52,
    ingredientes: [
      { insumoId: 'INS-15', cantidad: 90 },
      { insumoId: 'INS-20', cantidad: 60 },
      { insumoId: 'INS-26', cantidad: 15 },
      { insumoId: 'INS-24', cantidad: 15 },
      { insumoId: 'INS-22', cantidad: 2 },
      { insumoId: 'INS-17', cantidad: 180 },
      g('INS-27', 0.25),
    ],
  },
  {
    id: 'REC-03',
    nombre: 'Calimocho',
    cristaleria: 'Highball',
    metodo: 'Construido',
    garnitura: 'Twist de naranja',
    precio: 120,
    costoDoc: 24.31,
    ingredientes: [
      { insumoId: 'INS-15', cantidad: 90 },
      { insumoId: 'INS-19', cantidad: 120 },
      { insumoId: 'INS-17', cantidad: 180 },
      g('INS-29', 0.25),
    ],
  },
  {
    id: 'REC-04',
    nombre: 'Negroni',
    cristaleria: 'Old Fashioned',
    metodo: 'Refrescado',
    garnitura: 'Gajo de naranja',
    precio: 270,
    costoDoc: 53.95,
    ingredientes: [
      { insumoId: 'INS-03', cantidad: 30 },
      { insumoId: 'INS-06', cantidad: 30 },
      { insumoId: 'INS-13', cantidad: 30 },
      { insumoId: 'INS-17', cantidad: 150 },
      g('INS-29', 0.25),
    ],
  },
  {
    id: 'REC-05',
    nombre: 'Sbagliato',
    cristaleria: 'Old Fashioned',
    metodo: 'Construido',
    garnitura: 'Twist limón eureka',
    precio: 215,
    costoDoc: 43.35,
    ingredientes: [
      { insumoId: 'INS-16', cantidad: 60 },
      { insumoId: 'INS-06', cantidad: 30 },
      { insumoId: 'INS-13', cantidad: 30 },
      { insumoId: 'INS-17', cantidad: 150 },
      g('INS-27', 0.25),
    ],
  },
  {
    id: 'REC-06',
    nombre: 'Carajillo',
    cristaleria: 'Old Fashioned / Martini',
    metodo: 'Shakeado',
    garnitura: '3 granos de café',
    precio: 270,
    costoDoc: 54.29,
    ingredientes: [
      { insumoId: 'INS-10', cantidad: 60 },
      { insumoId: 'INS-25', cantidad: 1 },
      { insumoId: 'INS-17', cantidad: 150 },
    ],
  },
  {
    id: 'REC-07',
    nombre: 'Espresso Martini',
    cristaleria: 'Sidra 500 ml',
    metodo: 'Shakeado',
    garnitura: '3 granos de café',
    precio: 180,
    costoDoc: 35.93,
    ingredientes: [
      { insumoId: 'INS-04', cantidad: 45 },
      { insumoId: 'INS-11', cantidad: 15 },
      { insumoId: 'INS-25', cantidad: 1 },
      { insumoId: 'INS-17', cantidad: 150 },
    ],
  },
  {
    id: 'REC-08',
    nombre: 'Gin & Tonic',
    cristaleria: 'Martini',
    metodo: 'Construido',
    garnitura: 'Aceituna gordal',
    precio: 250,
    costoDoc: 50.54,
    ingredientes: [
      { insumoId: 'INS-03', cantidad: 60 },
      { insumoId: 'INS-18', cantidad: 120 },
      { insumoId: 'INS-17', cantidad: 150 },
      g('INS-31', 1),
    ],
  },
  {
    id: 'REC-09',
    nombre: 'Martini Seco',
    cristaleria: 'Martini',
    metodo: 'Refrescado',
    garnitura: 'Aceituna gordal',
    precio: 260,
    costoDoc: 52.25,
    ingredientes: [
      { insumoId: 'INS-03', cantidad: 60 },
      { insumoId: 'INS-14', cantidad: 10 },
      { insumoId: 'INS-17', cantidad: 150 },
      g('INS-31', 1),
    ],
  },
  {
    id: 'REC-10',
    nombre: 'Martini Sucio',
    cristaleria: 'Sidra 500 ml',
    metodo: 'Refrescado',
    garnitura: 'Popote',
    precio: 220,
    costoDoc: 43.86,
    ingredientes: [
      { insumoId: 'INS-04', cantidad: 60 },
      { insumoId: 'INS-14', cantidad: 15 },
      { insumoId: 'INS-21', cantidad: 15 },
      { insumoId: 'INS-17', cantidad: 150 },
      g('INS-34', 1),
    ],
  },
  {
    id: 'REC-11',
    nombre: 'Mojito',
    cristaleria: 'Old Fashioned',
    metodo: 'Macerado',
    garnitura: 'Ring sal gusano + naranja',
    precio: 115,
    costoDoc: 23.13,
    ingredientes: [
      { insumoId: 'INS-05', cantidad: 60 },
      { insumoId: 'INS-26', cantidad: 30 },
      { insumoId: 'INS-24', cantidad: 22.5 },
      { insumoId: 'INS-20', cantidad: 60 },
      { insumoId: 'INS-30', cantidad: 1 },
      { insumoId: 'INS-17', cantidad: 150 },
      g('INS-33', 2),
      g('INS-29', 0.25),
    ],
  },
  {
    id: 'REC-12',
    nombre: 'Margarita',
    cristaleria: 'Martini',
    metodo: 'Shakeado',
    garnitura: 'Ring sal mar + limón eureka',
    precio: 325,
    costoDoc: 64.91,
    ingredientes: [
      { insumoId: 'INS-02', cantidad: 60 },
      { insumoId: 'INS-12', cantidad: 30 },
      { insumoId: 'INS-26', cantidad: 30 },
      { insumoId: 'INS-17', cantidad: 150 },
      g('INS-32', 2),
      g('INS-27', 0.25),
    ],
  },
  {
    id: 'REC-13',
    nombre: 'Long Island Tea',
    cristaleria: 'Vaso sidra',
    metodo: 'Construido / Shakeado',
    garnitura: 'Rodaja limón eureka',
    precio: 200,
    costoDoc: 39.9,
    ingredientes: [
      { insumoId: 'INS-02', cantidad: 15 },
      { insumoId: 'INS-04', cantidad: 15 },
      { insumoId: 'INS-05', cantidad: 15 },
      { insumoId: 'INS-03', cantidad: 15 },
      { insumoId: 'INS-12', cantidad: 15 },
      { insumoId: 'INS-26', cantidad: 22.5 },
      { insumoId: 'INS-19', cantidad: 30 },
      { insumoId: 'INS-17', cantidad: 180 },
      g('INS-27', 0.25),
    ],
  },
  {
    id: 'REC-14',
    nombre: 'Cuba Libre',
    cristaleria: 'Highball',
    metodo: 'Construido',
    garnitura: 'Sin garnitura',
    precio: 120,
    costoDoc: 23.63,
    ingredientes: [
      { insumoId: 'INS-05', cantidad: 60 },
      { insumoId: 'INS-26', cantidad: 15 },
      { insumoId: 'INS-19', cantidad: 120 },
      { insumoId: 'INS-20', cantidad: 30 },
      { insumoId: 'INS-17', cantidad: 180 },
    ],
  },
  {
    id: 'REC-15',
    nombre: 'Bloody Mary',
    cristaleria: 'Vaso sidra',
    metodo: 'Roll',
    garnitura: 'Sin garnitura',
    precio: 130,
    costoDoc: 26.36,
    ingredientes: [
      { insumoId: 'INS-04', cantidad: 45 },
      { insumoId: 'INS-23', cantidad: 180 },
      { insumoId: 'INS-17', cantidad: 180 },
    ],
  },
  {
    id: 'REC-16',
    nombre: 'Saint Germaine Spritz',
    cristaleria: 'Copa de vino',
    metodo: 'Construido',
    garnitura: 'Sin garnitura',
    precio: 410,
    costoDoc: 82.43,
    ingredientes: [
      { insumoId: 'INS-08', cantidad: 60 },
      { insumoId: 'INS-16', cantidad: 90 },
      { insumoId: 'INS-20', cantidad: 60 },
      { insumoId: 'INS-17', cantidad: 180 },
    ],
  },
  {
    id: 'REC-17',
    nombre: 'Aperol Spritz',
    cristaleria: 'Copa de vino',
    metodo: 'Construido',
    garnitura: 'Twist limón eureka',
    precio: 270,
    costoDoc: 53.81,
    ingredientes: [
      { insumoId: 'INS-07', cantidad: 60 },
      { insumoId: 'INS-16', cantidad: 90 },
      { insumoId: 'INS-20', cantidad: 60 },
      { insumoId: 'INS-17', cantidad: 180 },
      g('INS-27', 0.25),
    ],
  },
  {
    id: 'REC-18',
    nombre: 'Italicus Spritz',
    cristaleria: 'Copa de vino',
    metodo: 'Construido',
    garnitura: 'Rodaja de naranja',
    precio: 560,
    costoDoc: 112.28,
    ingredientes: [
      { insumoId: 'INS-09', cantidad: 60 },
      { insumoId: 'INS-16', cantidad: 90 },
      { insumoId: 'INS-20', cantidad: 60 },
      { insumoId: 'INS-17', cantidad: 180 },
      g('INS-29', 0.25),
    ],
  },
]
